### ISSUE TITLE
LibreOffice menubar unreadable

### ISSUE THREAD

**Issue by supaiku-o** [tista500/Adapta#43] opened 2016-04-10 10:15 UTC
Using LibreOffice with GTK3 backend results in unreadable menubar.

![bildschirmfoto von 2016-04-10 12-14-07](https://cloud.githubusercontent.com/assets/1311798/14409522/c1cf5202-ff15-11e5-8bcc-1d814a584e0d.png)

**Comment by tista500** [comment] 2016-04-10 12:42
@supaiku-o,

This is the duplicate of this issue: #35.
And this is not theme-related, but happens with the combo "Gtk+ 3.20 + LibreOffice 5.1.1" + dark menubar on light variant". Seems LibreOffice could not run on Gtk+ 3.20.

Use Gtk+ 2.0 backend.

Regards.

**Comment by zoutiyx** [comment] 2016-04-11 23:15
@supaiku-o ,

File a bug report here: https://bugs.documentfoundation.org/enter_bug.cgi

**Comment by stelariusinfinitek** [comment] 2016-06-05 18:05
A workaround for this issue : 

- Open this file with a text editor :  **/etc/profile.d/libreoffice-fresh.sh** (if you are using Libreoffice Fresh)
- Uncomment **export SAL_USE_VCLPLUGIN=gtk**
- Save, exit, reboot. :)

**Comment by tista500** [comment] 2016-06-13 09:30
Greetings,

Fix was committed: https://github.com/tista500/Adapta/commit/07714caa2c6b260cefdb8cafc9af3b44cd0bbb2d

Regards.

**Closed by tista500** 2016-06-13 09:30 UTC
Labels: wontfix
