### ISSUE TITLE
Doubled entrees in gtk.css & gtk-dark.css

### ISSUE THREAD

**Issue by glitsj16** [tista500/Adapta#147] opened 2016-06-23 14:05 UTC
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.6-1
 * Desktop environment - gnome
 ```

**Adapta version (if you knew)**
3.21.3 (git20160621)

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Several doubled entrees in gtk.css & gtk-dark.css for either background-color, box-shadow, color or all 3

**Steps to reproduce (if you knew)**

**Expected behaviour**
Single CSS values for the relevant entrees.

**Other Note (feature-request, question, etc...)**

Hi, noticing a bunch of doubled entrees in gtk.css & gtk-dark.css (3.20). I haven't checked gtk next yet, but if you need me too I'll be happy to check and add info here. But I suspect your 'debug' skills will pick up the scent when looking at the list here.. I put the line numbers in, hope this helps to track down what's causing this.

* doubled entree 'color':

	809+
	    .button.destructive-action:active {
		box-shadow: 0 2px 2px rgba(0, 0, 0, 0.12), 0 3px 4px rgba(0, 0, 0, 0.2), inset 0 1px rgba(255, 255, 255, 0.07);
		color: #263238;
		transition-duration: 0;
		animation: ripple_effect 0.2s cubic-bezier(0.4, 0, 0.2, 1) forwards;
		background-color: #00BCD4;
		color: #FFFFFF; }

	1346+
	    modelbutton.flat:checked,
	    .menuitem.button.flat:checked,
	    .ssd decoration .menuitem.button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		color: #263238; }

	1694+
	    .osd toolbar button:checked, toolbar.osd button:checked, .app-notification button:checked,
	    .app-notification.frame button:checked, GeditViewFrame .gedit-search-slider button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		border-image: none;
		color: #4DB6AC;
		box-shadow: none; }

	1744+
	    toolbar button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		border-image: -gtk-gradient(radial, center bottom, 0, center bottom, 0.5, to(#00BCD4), to(transparent)) 0 0 2/0 0 2px;
		background-color: transparent;
		color: #263238;
		box-shadow: none; }

	3272+
	    popover.background .linked > button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		color: #263238;
		background-color: transparent; }

	6041+
	    messagedialog.background .dialog-action-area button:checked,
	    messagedialog.background .dialog-action-area .linked > button:checked, messagedialog.csd.background .dialog-action-area button:checked,
	    messagedialog.csd.background .dialog-action-area .linked > button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		color: rgba(77, 182, 172, 0.9); }

	6436+
	    .info button:checked,
	    .question button:checked,
	    .warning button:checked,
	    .error button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		color: #263238; }

	8419+
	    actionbar button:checked,
	    actionbar .linked > button.image-button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		border-image: -gtk-gradient(radial, center bottom, 0, center bottom, 0.5, to(#00BCD4), to(transparent)) 0 0 2/0 0 2px;
		background-color: transparent;
		color: #263238;
		box-shadow: none; }

	11232+
	     .budgie-session-dialog button:checked,
	    .budgie-session-dialog .linked > button:checked,
	    .budgie-polkit-dialog button:checked,
	    .budgie-polkit-dialog .linked > button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		color: rgba(77, 182, 172, 0.9); }

	11379+
	     window grid.vertical > widget > box > button.image-button:checked {
		background-color: alpha(currentColor, 0.2);
		color: #263238;
		border-image: -gtk-gradient(radial, center bottom, 0, center bottom, 0.5, to(#00BCD4), to(transparent)) 0 0 2/0 0 2px;
		background-color: transparent;
		color: #263238;
		box-shadow: none; }

	7104+
	    .csd headerbar button.titlebutton.close:hover,
	    .csd headerbar.selection-mode button.titlebutton.close:hover,
	    .csd .titlebar button.titlebutton.close:hover,
	    .csd .titlebar.selection-mode button.titlebutton.close:hover {
		box-shadow: 0 2px 2px rgba(0, 0, 0, 0.12), 0 3px 4px rgba(0, 0, 0, 0.2), inset 0 1px rgba(255, 255, 255, 0.07);
		background-image: -gtk-gradient(radial, center center, 0, center center, 0.5, to(alpha(currentColor, 0)), to(transparent)), linear-gradient(to bottom, alpha(currentColor, 0));
		color: #171717;
		color: #FFFFFF;
		background-color: #D81F1F; }

	7116+
	    .csd headerbar button.titlebutton.close:active,
	    .csd headerbar.selection-mode button.titlebutton.close:active,
	    .csd .titlebar button.titlebutton.close:active,
	    .csd .titlebar.selection-mode button.titlebutton.close:active {
		box-shadow: 0 2px 2px rgba(0, 0, 0, 0.12), 0 3px 4px rgba(0, 0, 0, 0.2), inset 0 1px rgba(255, 255, 255, 0.07);
		color: #171717;
		transition-duration: 0;
		animation: ripple_effect 0.2s cubic-bezier(0.4, 0, 0.2, 1) forwards;
		color: #FFFFFF;
		background-color: #4C4C4C; }

* doubled entree 'background-color':

	11205+
	    .budgie-session-dialog button,
	    .budgie-session-dialog .linked > button,
	    .budgie-polkit-dialog button,
	    .budgie-polkit-dialog .linked > button {
		box-shadow: none;
		background-color: transparent;
		background-image: -gtk-gradient(radial, center center, 0, center center, 0.5, to(alpha(currentColor, 0)), to(transparent)), linear-gradient(to bottom, alpha(currentColor, 0));
		padding: 0.69767rem 0.99775rem 0.8027rem;
		border: 2px solid transparent;
		border-radius: 0;
		color: rgba(19, 177, 213, 0.9);
		background-color: transparent;
		background-size: 9.93998rem 9.93998rem, auto; }

* doubled entree 'box-shadow'

	1466+
	    spinbutton:not(.vertical) button {
		box-shadow: none;
		background-color: transparent;
		background-image: -gtk-gradient(radial, center center, 0, center center, 0.5, to(alpha(currentColor, 0)), to(transparent)), linear-gradient(to bottom, alpha(currentColor, 0));
		min-width: 0.99775rem;
		min-height: 0.99775rem;
		padding: 0 0.54764rem 0;
		border: solid 0.20255rem transparent;
		border-radius: 100px;
		-gtk-outline-radius: 100px;
		background: none;
		background-size: contain;
		color: rgba(38, 50, 56, 0.75);
		box-shadow: none;
		transition-property: opacity, color, background-color, background-image, box-shadow; }

* doubled entree 'box-shadow', 'background-color' & 'color':

	6014+
	    messagedialog.background .dialog-action-area button,
	    messagedialog.background .dialog-action-area .linked > button, messagedialog.csd.background .dialog-action-area button,
	    messagedialog.csd.background .dialog-action-area .linked > button {
		box-shadow: none;
		background-color: transparent;
		background-image: -gtk-gradient(radial, center center, 0, center center, 0.5, to(alpha(currentColor, 0)), to(transparent)), linear-gradient(to bottom, alpha(currentColor, 0));
		border: 2px solid transparent;
		border-radius: 0;
		color: rgba(220, 220, 220, 0.75);
		font-size: initial;
		font-weight: 700;
		background-size: 9.93998rem 9.93998rem, auto;
		box-shadow: none;
		background-color: transparent;
		color: rgba(19, 177, 213, 0.9); }

**Comment by tista500** [comment] 2016-06-23 14:12
@glitsj16,

What was the actual problem caused by generated CSSs and what is the benefit to debug those CSSs?

Regards.

**Comment by tista500** [comment] 2016-06-23 14:25
Ah I see...

You meant these?:

```diff
diff --git a/gtk/sass/3.18/_common.scss b/gtk/sass/3.18/_common.scss
index 566f690..65cdfdf 100644
--- a/gtk/sass/3.18/_common.scss
+++ b/gtk/sass/3.18/_common.scss
@@ -188,9 +188,7 @@ GtkAssistant {
     // apply suggested-action button for "Next" and "Back"
     // last -> "cancel", nth -> "Next" and "Back", that's weird.
     .button.flat:not(:last-child) {
-      @include button(normal);
-      background-color: $suggested_color;
-      color: $secondary_selected_fg_color;
+      @include button(normal, $suggested_color, $secondary_selected_fg_color);
       &:hover {
         @include button(hover);
         color: $selected_fg_color;
```

**Comment by glitsj16** [comment] 2016-06-23 14:32
@tista500,

I don't have gtk-3.18 'Arch Linux' is on 3.20. But I suspect it is indeed those rules that cause the doubling of some entrees. Started to notice it as of yesterday.. I don't actually notice a visual glitch. I was going over the code to check some things and I noticed these doubled entrees. More of a cosmetics thing perhaps, just thought you might want to know..

**Comment by tista500** [comment] 2016-06-23 14:36
??

Weren't you takling about include functions in sass? :(

Regards.

**Comment by glitsj16** [comment] 2016-06-23 14:44
I'll add some more context here later if you don't mind, gotta get the kids from school.. After the recent code refactoring (building CSS + png's at build time) I have been experiencing some issues. Reporting back in a few hours, thanks for your patience,

Regards

**Comment by glitsj16** [comment] 2016-06-23 21:37
Perhaps an example will explain better what I'm getting at. It shows my reasoning reading the scss code and tracking how the separate pieces fit together to produce the actual CSS. Please correct me where I'm wrong, it's quite possible :-) I picked an easier target from the above list to keep things at bay for now..

gtk-3.20/gtk.css:
...
 _this is the code part we'll be looking at here, to track down where the double color entree stems from_:
modelbutton.flat:checked,
.menuitem.button.flat:checked,
.ssd decoration .menuitem.button:checked {
    background-color: alpha(currentColor, 0.2);
    **color: #263238;
    color: #263238;** }

*** reconstruction logic ***

(1) _common.css:
...
// menu buttons on GtkPopover
modelbutton.flat,
.menuitem.button.flat {
  @include button(flat-normal);
  min-height: rem(26.6px);
  padding: rem(2.7px) rem(5.3px) rem(3.3px);
  outline-offset: rem(-1px);
  background-size: $text_button_small;
  color: $secondary_fg_color;
  transition: none;
  &:hover {
    @include button(flat-hover);
    color: $fg_color;
  }
  &:active {
    @include button(flat-active);
    color: $fg_color;
  }
  &:checked {							<--- example:
    **@include button(flat-checked);**             * includes from _drawing.scss (button drawing function)
    **color: $fg_color;**						* (1.1) defines color value
  }
  &:checked:disabled {
    @include button(flat-checked-insensitive);
    color: $insensitive_fg_color;
  }
  &:disabled {
    @include button(flat-insensitive);
    color: $insensitive_secondary_fg_color;
  }

  check,
  radio {
    &:first-child { margin-right: rem(13.3px); }
    &:last-child { margin-left: rem(13.3px); }
  }
}

(2) _drawing.scss:
...
//
// Button drawing function
//
// $t:    button type,
// $c:    base button color for colored* types
// $tc:   optional text color for colored* types
//
// possible $t values:
// normal, hover, active, insensitive, checked, checked-insensitive,
// flat-normal, flat-hover, flat-active, flat-insensitive, flat-checked,
// flat-checked-insensitive, undecorated
//

...

  @else if $t==flat-checked {
  //
  // checked flat button
  //
    background-color: $track_color;
    **color: $fg_color;**                                                * (2.1) defines color value
  }

(3) result --> generated gtk.css

modelbutton.flat:checked,
.menuitem.button.flat:checked,
.ssd decoration .menuitem.button:checked {
    background-color: alpha(currentColor, 0.2);
    **color: #263238;**                                      * from _drawing.scss (2.1)
    **color: #263238;** }                                   * from _common.scss (1.1)

Do you see what I'm getting at?

**Comment by tista500** [comment] 2016-06-23 21:54
Refactoring already started in another branch, so you don't have to track those down anymore...

Regards.

**Comment by glitsj16** [comment] 2016-06-23 21:58
Okay, thanks for looking into it. I'll leave the issue open for now.

Regards.

**Comment by tista500** [comment] 2016-06-24 01:39
Now I've merged wip/refactor branch into master...

Almost fixed.

Regards.

**Closed by tista500** 2016-06-24 01:39 UTC
