### ISSUE TITLE
Deselected text in Cinnamon is illegibly light

### ISSUE THREAD

**Issue by mmirg** [tista500/Adapta#208] opened 2016-08-27 13:36 UTC
**Reporter info**

 ```
 * Distribution - Gentoo
 * Gtk+ 3.0 version - 3.20.8
 * Desktop environment - Cinnamon 3.0.6
 ```

**Adapta version (if you knew)**
3.21.4.239

**Related Application and/or Shell theming (or name of widget)**
Notifications, settings panel

**Actual issue**
Deselected text appears in a nearly invisible light text on light background.

**Steps to reproduce (if you knew)**
Select an options in System Settings then press the back arrow to return to the main settings panel,  The previously selected option will appear in a washed out white text with a faint teal drop shadow.  Send multiple notifications and all but the most recent notification will be in a similar difficult to read color.

**Expected behaviour**
Deselected text should be differentiated from ordinary text but still legible.

**Other Note (feature-request, question, etc...)**

![notification](https://cloud.githubusercontent.com/assets/4317194/18027720/ae37ba22-6c6b-11e6-8a7a-d298ca58a1be.png)

See "Fonts"
![screenshot from 2016-08-27 15-22-25](https://cloud.githubusercontent.com/assets/4317194/18027726/d6a10770-6c6b-11e6-90a0-79f2ba4a33c3.png)

**Comment by tista500** [comment] 2016-08-28 05:22
> The previously selected option will appear in a washed out

That is not the feature in Gtk+ 3.20 and Gnome-Control-Center. In Gnome-Control-Center, there's no reason to keep grabbing 'previously selected' iconview, so I won't do as well. And this issue is related to Cinnamon-Control-Center what still stack with Gtk+ 3.14 codebase with "half-baked" conversion to Gtk+ 3.20.x...:/ I really dislike such developments in upstream because those will take theme designer's time in every-time to implement (revive) ancient Gtk+ versioned codebase "unneeded".

Anyway workaround for Cinnamon-Control-Center was committed: https://github.com/tista500/Adapta/commit/44854461c7217def16fec1a25761332feadf752b

And I could not reproduce such notification issue.

**Comment by tista500** [comment] 2016-09-04 18:06
No response, Closed...

**Closed by tista500** 2016-09-04 18:06 UTC

**Comment by mmirg** [comment] 2016-09-05 16:10
This commit fixed the deselected icon issue for me.  The notification is still a mystery, but it seems like a corner case that is not critical.  I'm not even able to reproduce it reliably.

**Comment by tista500** [comment] 2016-11-04 11:04
See #269, multi-lined notification texts are fixed, I hope...

Regards.

**Comment by mmirg** [comment] 2016-11-29 16:30
Yes, multi-lined notifications seem to be fixed.  Thank you for the update.
