### ISSUE TITLE
my atom menu bar was worng

### ISSUE THREAD

**Issue by juvevood** [tista500/Adapta#216] opened 2016-09-09 10:00 UTC
**Reporter info**

 ```
 * Gtk+ 3.0 3.20.2
 * Desktop environment:Archlinux 
 * Adapta version :3.21.5.66
 ```

![black](https://cloud.githubusercontent.com/assets/1421513/18383255/4b8d70b8-764a-11e6-9ea3-c5f93e631269.png)

**Comment by Rahh1112** [comment] 2016-09-10 14:37
I can confirm that too..
 * Gtk+ 3.0 3.20.2
 * Desktop environment: Gnome 3.20 on ARCH
 * Adapta version :3.21.5.66

**Comment by tista500** [comment] 2016-09-10 15:14
Greetings,
I could not reproduce with Atom 1.10.2 from official Github:

![screenshot from 2016-09-11 00-11-52](https://cloud.githubusercontent.com/assets/6073622/18411558/940dd3ee-77b4-11e6-9559-245a38af9bc6.png)

Regards.

**Comment by Rahh1112** [comment] 2016-09-11 01:16
Maybe it's only on GNOME?
![captura de tela de 2016-09-10 22-14-52](https://cloud.githubusercontent.com/assets/12601769/18414552/24f4264e-77a4-11e6-8cdd-369e70c4528f.png)

**Comment by tista500** [comment] 2016-09-11 02:18
> Maybe it's only on GNOME?

I don't think so.
![screenshot from 2016-09-11 11-11-23](https://cloud.githubusercontent.com/assets/6073622/18414734/c0f318c2-7810-11e6-9e7e-59df8b98d97e.png)

Because the backend of Atom is Gtk+ 2.x and it's mostly independent from any desktop environments.

**Comment by GhettoGirl** [comment] 2016-09-11 09:06
On Arch Linux the Atom editor is directly executed using Electron, they don't use the offered binaries which comes with Electron [GTK2]. As an extend Electron on Arch uses GTK3 and not GTK2. So in short: Atom on Arch = GTK3.

Here is a screenshot of my menu bar using the light theme.
![screenshot_20160911_110216](https://cloud.githubusercontent.com/assets/13280758/18416268/ccb6ef90-780f-11e6-8590-eb87cc1c4e32.png)

**Comment by tista500** [comment] 2016-09-11 11:15
@GhettoGirl,

Why Arch contributors did such "hajf-baked" patchworks? Since `menuitem` node should contain the `label` node (and `image` node if it was needed)... :(
And it seems to lack the node of GtkWindow as well. So you mean you guys want me to set `window > manubar > menuitem` styling only for Atom in Arch (completely non-sense)?

Regards.

**Comment by GhettoGirl** [comment] 2016-09-11 11:25
@tista500
I don't use Gtk for development, so I have no idea what you are talking about here :(
The patch was only for the menu bar though. Here is the full patch set which is applied on Electron. Maybe you find what you are looking for somewhere.
[electron.zip](https://github.com/tista500/Adapta/files/465925/electron.zip)

--

As workaround someone could go with the bundled version of Atom which uses Electron with Gtk2. Which is indeed working, I just tried it.

**Comment by tista500** [comment] 2016-09-11 12:26
1st trial was committed: https://github.com/tista500/Adapta/commit/ee24956bda9cd119074160f52bfbbba7cf7c35aa

Check if it could help Arch users...

Regards.

**Comment by tista500** [comment] 2016-09-11 12:26
1st trial was committed: https://github.com/tista500/Adapta/commit/ee24956bda9cd119074160f52bfbbba7cf7c35aa

Check if it could help Arch users...

Regards.

**Comment by tista500** [comment] 2016-09-11 12:46
2nd trial was committed: https://github.com/tista500/Adapta/commit/d981b23dd4920a60032c5c2a44641233ee8cba92

Fixed 1st incorrect commit above... So please check this again...

Regards.

**Comment by GhettoGirl** [comment] 2016-09-11 13:37
Nope, still the same foreground color.

**Comment by tista500** [comment] 2016-09-11 13:48
3rd trial was committed: https://github.com/tista500/Adapta/commit/f0ebdf309dee99c3a02903d5fc403b2bf32fec70

If this commit did not work properly, I won't do anything more...

Regards.

**Comment by GhettoGirl** [comment] 2016-09-11 13:56
That did the trick :+1: 
![screenshot_20160911_155345](https://cloud.githubusercontent.com/assets/13280758/18417734/2c006a9e-7838-11e6-8d50-841ab7947d34.png)

**Comment by tista500** [comment] 2016-09-11 14:30
OK...

But as of the shot above https://github.com/tista500/Adapta/issues/216#issuecomment-246155583 seems to fix the hover state of GtkMenu > GtkMenuItem as well... :(

Atom seems to draw hovered background of popup menus with the background of GtkMenuBar (Anyway I can't understand why that patch was accepted and committed)...

4th trial was committed: https://github.com/tista500/Adapta/commit/88073d1a560ec3b3d1837e860ff0dc0d389c77da

Check if this could fix the incorrect background-color of hovered menuitems in popup-menus...

Regards.

**Comment by GhettoGirl** [comment] 2016-09-11 15:05
Nope :(

![screenshot_20160911_165921](https://cloud.githubusercontent.com/assets/13280758/18418179/d6d55d9a-7841-11e6-9cea-510458d0f2b5.png)

**Comment by tista500** [comment] 2016-09-11 15:50
@GhettoGirl.

Ugghh... :(

Anyway 5th trial was committed: https://github.com/tista500/Adapta/commit/4932af3efc6926ea625b13341271a7a9401aa26b

I really hope this could finish the nightmare tonight...

Regards.

**Comment by GhettoGirl** [comment] 2016-09-11 17:18
@tista500

Nope, still the same.

And just FYI, this doesn't has anything to do with Atom, its "Electron with GTK3" specific. Just to demonstrate that to you I made a quick sample app in Electron :wink: 
And started it with `electron .`. The results are the same as in the Atom editor.
![screenshot_20160911_190708](https://cloud.githubusercontent.com/assets/13280758/18419057/6b31e47a-7853-11e6-82c5-d282e584545d.png)

Here the same app, but bundled using `electron-packager` which downloads the vanilla version of Electron - which uses GTK2. This is the version which Atom is using when downloading from the GitHub release page.
![screenshot_20160911_191506](https://cloud.githubusercontent.com/assets/13280758/18419119/5bc5d6a8-7854-11e6-90b5-3472358e6355.png)

**Comment by tista500** [comment] 2016-09-11 18:36
@GhettoGirl,

Yes. I committed "unspecified" fixes for generic `menubar` and `menuitem` node instead of Atom only. And just to clarify this issue is Adapta specific, right?

I haven't any clue what's wrong...

Regards.

**Comment by xpduyson** [comment] 2016-09-15 07:08
Can confirm this black select menu problem also happen on Chromium (GTK3 version) on Debian testing.
![screenshot from 2016-09-15 14-06-26](https://cloud.githubusercontent.com/assets/6981890/18541219/eab59028-7b4d-11e6-86ea-de7f664f28e2.png)

**Comment by tista500** [comment] 2016-09-15 08:55
@xpduyson,

If you don't have any patches, please stop bumping the issue since this issue was already tracked. Regardless "me, too", "affected +1" are usually meaningless in development.

**Comment by tista500** [comment] 2016-09-15 09:53
The final workaround was committed: https://github.com/tista500/Adapta/commit/dd1910208078c1ee86f13a56bd48d92e609c5de0

Gtk+ 3.x backend-ed Electron is out of control for me, so even if that commit may not work, I will not add any fixes for this issue...

Regards.

**Closed by tista500** 2016-09-15 09:53 UTC
Labels: enhancement, wontfix

**Comment by tista500** [comment] 2017-01-09 00:02
The appearance of context-menus should be fixed by this commit: https://github.com/adapta-project/adapta-gtk-theme/commit/87fc030b1c28e4effdd2f9e8a7f19cef93504a68

I hope that commit improved styling much better...
