### ISSUE TITLE
Problem with fonts in the shell

### ISSUE THREAD

**Issue by ivandotv** [tista500/Adapta#82] opened 2016-05-10 13:01 UTC
**Reporter info**

 ```
 * Distribution - ubuntu gnome 16.04
 * Gtk+ 3.0 version - GTK 3.18
 * Desktop environment - Gnome 3.18
 ```

**Adapta version (if you knew)**
lastest from the repository.

**Related Application and/or Shell theming (or name of widget)**

Shell

**Actual issue**
Fonts in the shell are not displaying correctly

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

![screenshot from 2016-05-10 11-31-02](https://cloud.githubusercontent.com/assets/390700/15142011/5b61ea5c-16a3-11e6-9211-25e919f21dd8.png)
![screenshot from 2016-05-10 11-31-21](https://cloud.githubusercontent.com/assets/390700/15142015/5db89832-16a3-11e6-9163-1ab78f6aaedf.png)

**Comment by pschichtel** [comment] 2016-05-10 13:05
I usually have that when I install the infinality patched libs while I'm already booted. A restart solved it for me

**Comment by tista500** [comment] 2016-05-10 13:12
Greetings,

Let me know your locales and font-name you've set as "Interface" in Gnome-Tweak-Tool.
Adapta supports `Roboto`, `Lato`, `Cantarell` and `Sans-Serif` in Gnome-shell.

Regards.

**Comment by ivandotv** [comment] 2016-05-10 13:21
I have never changed any fonts, restart doesn't help.
Inteface is Cantrell Regular 11

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=sr_RS
LC_TIME=sr_RS
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sr_RS
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sr_RS
LC_NAME=sr_RS
LC_ADDRESS=sr_RS
LC_TELEPHONE=sr_RS
LC_MEASUREMENT=sr_RS
LC_IDENTIFICATION=sr_RS
LC_ALL=
```

**Comment by tista500** [comment] 2016-05-10 13:50
@ivandotv,

I haven't any clue why `LANGUAGE` variable was empty, is it normal in your country?
So try `sudo update-locale LANGUAGE=en_US` and the reboot.

Regards.

**Comment by tista500** [comment] 2016-05-12 16:56
2days after any responses were not come so close this issue.

Regards.

**Closed by tista500** 2016-05-12 16:56 UTC
Labels: wontfix

**Comment by ivandotv** [comment] 2016-05-12 19:58
Updating language doesn't work. 
Restarting doesn't work.

**Comment by tista500** [comment] 2016-05-13 01:30
@ivandotv,

Sounds strange.
I've tried your locale but could not reproduce:
```
1. sudo apt install language-pack-sr
2. sudo update-locale LANGUAGE=sr_RS:en_US LANG=sr_RS.UTF-8
3. reboot
```
My font: Lato Regular 9pt
Gnome-Shell: 3.18.4 inside the chroot
Gtk+: 3.18.9-1ubuntu3
![screenshot from 2016-05-13 10-20-41](https://cloud.githubusercontent.com/assets/6073622/15235363/680a50d8-18f5-11e6-8bb5-0b7cf6d6e5ac.png)
There's no critical visual issues in my screenshot...

Regards.

**Comment by ivandotv** [comment] 2016-05-13 18:33
I've have tried Arc,Numix, and Paper. I don't get these issues with those themes.
Strange problem indeed.

**Comment by codeman6100** [comment] 2016-06-07 22:23
seems to be fixed in latest release

**Comment by HEXcube** [comment] 2016-07-11 19:10
Had this issue on two of my **Ubuntu GNOME 16.04LTS** machines at work.:worried: Occured both times during update. Did Adapta change default font or somthing last month?:confused: Anyway, I installed *Roboto* and *Lato* font packages ([fonts-roboto](https://launchpad.net/ubuntu/+source/fonts-roboto) and [fonts-lato](https://launchpad.net/ubuntu/+source/fonts-lato)) and that seems to have fixed the issue!:grin: @tista500  So, is it possible to include `fonts-lato` and `fonts-roboto` as `install-recommends` of Adapta theme's deb package for Ubuntu? :confused:

However, I couldn't reproduce the issue in Live boot of the same OS on my home machine. :open_mouth:  The latest Adapta package from PPA worked just fine without me needing to install any extra font!
