### ISSUE TITLE
Configure script does not find ruby-sass installed with bundler

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#140] opened 2016-06-21 22:59 UTC
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - irrelevant
 * Desktop environment - irrelevant
 ```

**Adapta version (if you knew)**
3.21.3.6

**Related Application and/or Shell theming (or name of widget)**
SASS / automake

**Actual issue**
I wanted to remove the dependency on a globally installed ruby-sass in the Archlinux AUR package I maintain.
As you provide a Gemfile I used ```bundle install``` to install the specified sass version, however after that, running the autogen.sh script will fail because it cannot find sass.

**Steps to reproduce (if you knew)**

Given that SASS is not installed globally:

```bash
pushd gtk/sass
bundle install
popd
./autogen.sh
```

**Expected behaviour**
./autogen.sh finds SASS in the local bundle

**Other Note (feature-request, question, etc...)**

I think the installation of the local ruby bundle should be part of the build scripts

**Comment by tista500** [comment] 2016-06-22 00:08
I'm not sure whether your approach makes sense or not in Debian, Ubuntu, Fedora and Suse...
Build-process should be enough with official packages via official repositories in both server-side and client-side. Most of distros already have sass ver.3.4.21 or higher in the latest release cycle.

And bundler can install `sass` in `/usr/local/bin` what can be found in automake, so I could not reproduce...

**Comment by GhettoGirl** [comment] 2016-06-22 06:35
I have installed sass using ```sudo gem install sass``` and have no problems. Bundler is in the official repositories ```sudo pacman -S ruby-bundler```.

This is a snippet from my bashrc
```bash
PATH="$PATH:/opt/ruby/gems/bin"         # Ruby gems (installed using 'gem install')
###   Ruby gems   ###
export GEM_PATH="/opt/ruby/gems"
```

and my ```/etc/gemrc``` file
```
# Read about the gemrc format at http://guides.rubygems.org/command-reference/#gem-environment

# --user-install is used to install to $HOME/.gem/ by default since we want to separate
#                pacman installed gems and gem installed gems
#gem: --user-install

# Specify installation prefix of ruby gems to a global directory, so every user can profit from them
# but keep it outside of /usr to seperate it from pacman installed gems.
gemhome: /opt/ruby/gems
```

Make sure you have your gem installation directory in your ```PATH``` and make sure ```which``` can find sass.

I also recommend you configure your ruby environment similar to mine so gems are installed on the root filesystem and not in your users home directory.
After that you should have no more problem with the configure script.

Regards

**Comment by pschichtel** [comment] 2016-06-22 08:08
Well @tista500 I guessed you defined the Gemfile for a reason and in your scripts you never call sass directly, but also through ```bundle exec sass``` which is usually used when executables are installed locally through bundler (because these exeuctables will not be in the PATH).

From my limited experience with writing and deploying ruby code, the trend seems to be not relying on global gems and installing everything locally (local = in the project's bundle directory) to guarantee a consistent build.

@GhettoGirl the problem is not installing/running SASS, but that automake does not detect the locally installed sass executable, because it's not in the PATH (and it should not have to be)

**Comment by pschichtel** [comment] 2016-06-22 22:29
I've worked around this by adding the local bundle directory's bin folder to the PATH, just to pass automake's check.

I think it would also be great to move the (identical) Gemfile's to the base directory, as currently two ```bundle install```s are necessary.

**Comment by tista500** [comment] 2016-06-22 22:36
@pschichtel,

What is the "base directory"?
You meant `$(srctopdir)`?

Regards.

**Comment by pschichtel** [comment] 2016-06-22 22:37
The root directory of the git repository (and thus also the source tarball)

**Comment by tista500** [comment] 2016-06-22 23:44
Committed: https://github.com/tista500/Adapta/commit/78a59c9be795a8f1cba7b5827f8e0899da218e04

Closed.

**Closed by tista500** 2016-06-22 23:44 UTC
