### ISSUE TITLE
A small grey dot at the edge of the header bar

### ISSUE THREAD

**Issue by Feichtmeier** [tista500/Adapta#156] opened 2016-07-02 07:35 UTC
**Reporter info**
![bildschirmfoto vom 2016-07-02 09-25-24](https://cloud.githubusercontent.com/assets/15329494/16539049/426f4036-4037-11e6-88fc-2ecf0588244a.png)
![bildschirmfoto vom 2016-07-02 09-27-28](https://cloud.githubusercontent.com/assets/15329494/16539051/4f34b59e-4037-11e6-87bb-bd46fc33136e.png)

 ```
 * Distribution - ubuntu 16.04 
 * Gtk+ 3.0 version - 3.18.9-1
 * Desktop environment - unity
 ```

**Adapta version (if you knew)**
Always up to date with this ppa, didn't find the concret version

**Related Application and/or Shell theming (or name of widget)**
Nautilus 3.143.3

**Actual issue**
There is a small bright grey pixel at the edges of the Nautilus header bar

**Steps to reproduce (if you knew)**
Apply adatpa gtk theme in ubuntu 16.04 and open nautilus

**Expected behaviour**

**Other Note (feature-request, question, etc...)**
Super cool gtk theme! Thank you for your work!!!!

**Comment by tista500** [comment] 2016-07-02 11:17
@Feichtmeier,

This is the duplicate of this issue: https://github.com/tista500/Adapta/issues/124
And it's completely upstream (compiz) issue.

However, now I've committed ugly workaround for those visual issues: https://github.com/tista500/Adapta/commit/b013a4f4edd7c2d551d940db9b20a9197cfa9f01

I really dislike those canonical's approaches, employing ancient versioned Nautilus to mixin' into Gtk+ 3.18.x and stupid behaviour of Compiz. So Xenial was the worst release for me... :(

Regards.

**Closed** 2016-07-02 21:47 UTC
Labels: enhancement
