### ISSUE TITLE
Some font color is too similar to background color in  terminal color scheme

### ISSUE THREAD

**Issue by caoli5288** [tista500/Adapta#217] opened 2016-09-13 04:38 UTC
```
 * fedora24
 * gtk3-3.20.9
 * gnome
 ```

**Adapta version (if you knew)**
adapta-gtk-theme_3.21.5+git20160911

**Related Application and/or Shell theming (or name of widget)**
gnome-terminal

**Actual issue**
![2016-09-13 12-32-27](https://cloud.githubusercontent.com/assets/3120587/18461680/962e0606-7941-11e6-8f9f-266869ed8b73.png)

Some font color is too similar to background color in  terminal color scheme.

**Comment by tista500** [comment] 2016-09-13 09:02
I can't get the point... :(
In Gnome-terminal 3.19.x or higher, we can switch the colour-variant and can change the colour-profile via settings, too. So what you want me to do?

Anyway workaround was committed: https://github.com/tista500/Adapta/commit/da92a8fc78f68f2c62f35c6726e2b96b9d1d5bf4

Please note "expected behaviour" in issue report as well...

Regards.

**Closed** 2016-09-13 09:02 UTC

**Comment by caoli5288** [comment] 2016-09-13 12:45
@tista500 Yes? I don't change colour-profile via settings just "use system theme colour"

**Comment by caoli5288** [comment] 2016-09-19 12:38
Please reopen this issue. it still not resolved. :-(

**Comment by tista500** [comment] 2016-09-19 15:46
No. It "should" be fixed.

Because I've already rebuilt gnome-terminal 3.20.2 based on these 2 patches:
http://pkgs.fedoraproject.org/cgit/rpms/gnome-terminal.git/tree/gnome-terminal-transparency-notify.patch?h=f24&id=5332c9d2b2710de9c096915b1a7e54b5ccc7ec07
http://pkgs.fedoraproject.org/cgit/rpms/gnome-terminal.git/tree/0001-build-Don-t-treat-warnings-as-errors.patch?h=f24&id=5332c9d2b2710de9c096915b1a7e54b5ccc7ec07
(I've removed some parts related to libvte-2.91 and translations since notification was very fedora specific)

Those patches are used in Fedora24 stcok packaging, and I could confirm those patches can run with my fix on my Ubuntu 16.10 (Gtk+ 3.20.9). Gnome-Terminal seems OK as I expected, see my shot:

![screenshot from 2016-09-20 00-37-27](https://cloud.githubusercontent.com/assets/6073622/18638331/aee08b2c-7eca-11e6-97ca-dca1840cdeb2.png)

**Comment by caoli5288** [comment] 2016-09-19 16:42
Interesting.:-/ I install theme by unpack deb from PPA(`adapta-gtk-theme_3.21.6+git20160918-0ubuntu1-xenial1_all.deb`). Will this lead problem(I think will not)? Even `dmesg` I got different color with your. A very dark yellow.

![2016-09-20 00-36-53](https://cloud.githubusercontent.com/assets/3120587/18640381/7d3b592a-7e5d-11e6-8691-72342927b9d6.png)

And `htop` still hard to watch.

![2016-09-20 00-40-44](https://cloud.githubusercontent.com/assets/3120587/18640501/1dccf8d0-7e5e-11e6-8137-54bef1cbaca7.png)

How can I do? I need your help :-\

**Comment by caoli5288** [comment] 2016-09-19 16:52
Oh my god so foolish I am and the gnome-terminal's UI designer. Most font color controlled under `Palette` option not `Text and Background Color`. :-<

Thank you for your help. Feel sorry waste your time.

**Comment by tista500** [comment] 2016-09-19 17:08
No problem... ;)
