### ISSUE TITLE
High CPU Usage in xfce

### ISSUE THREAD

**Issue by lithces** [tista500/Adapta#223] opened 2016-09-20 10:33 UTC
**Reporter info**

 ```
 * Distribution - Fedora 24
 * Gtk+ 3.0 version - gtk3-3.20.9-1.fc24.x86_64
 * Desktop environment - xfce4-session-4.12.1-9.fc24.x86_64
 ```

**Adapta version (if you knew)**

3.21.6, installed from 'Copr repo for gtk-themes owned by heikoada' via dnf

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

When switched to Adapta theme, Xorg takes high cpu usage. Same issues even after reboot

**Steps to reproduce (if you knew)**

Switch to Adapta theme

**Expected behaviour**

Low CPU Usage

**Other Note (feature-request, question, etc...)**

**Comment by cameronleger** [comment] 2016-09-20 12:47
Previous related bug: #130 
Here's my comment from that issue:

I have some more informaton on this issue and can confirm it affects me as well with a similar setup:
Adapta: 3.21.5.2 (at the time of the report, however it still affects newer versions)
GTK: 3.20.9
Murrine: 0.98.2
XFCE: ~ 4.12.3

Similar performance hit happens with Flat-Plat 3.20.20160821, however it does not happen with 3.18.20160821. I do not see large differences between those versions, so I am using 3.18 for now. Seems to be an issue stemming from GTK3 versions, so I'm hoping that when 3.22 is released this may be resolved.

I tried compiling with the --disable-gtk_next flag, but that did not solve the performance hit.

I can provide any more information as requested.

**Comment by tista500** [comment] 2016-09-20 15:13
I've re-opened #130 and this is the duplicate of that issue.
Please post the issue to the original one...

Closed.

**Closed by tista500** 2016-09-20 15:13 UTC
