### ISSUE TITLE
Maximize button doesn't work for EasyTAG

### ISSUE THREAD

**Issue by stelariusinfinitek** [tista500/Adapta#93] opened 2016-05-16 16:17 UTC
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.20.4-2
 * Desktop environment - Xfce 4.12
 ```

**Adapta version (if you knew)** 846.aecc2c2-1 (git)

**Related Application and/or Shell theming (or name of widget)** EasyTAG

**Actual issue** When I click the Maximize button in

 EasyTAG, nothing happens. Also, double clicking the title bar does nothing too. It works with other themes.

**Steps to reproduce (if you knew)** Open EasyTAG. Try to maximize the window. Nothing happens.

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

![screenshot_2016-05-16_19-12-12](https://cloud.githubusercontent.com/assets/18717816/15295748/a04ea050-1b9a-11e6-8c8a-c5a6085992d3.png)

**Comment by tista500** [comment] 2016-05-17 08:44
I could not reproduce this issue in case Gtk+ 3.18.9. And I don't have any partitions employs the combo XFce4 & Gtk+ 3.20.x...

Hmm, Were there any warnings when launching it from terminal?

Regards.

**Comment by stelariusinfinitek** [comment] 2016-05-17 10:46
No errors in the terminal.

**Comment by tista500** [comment] 2016-05-17 11:17
> When I click the Maximize button in EasyTAG, nothing happens. Also, double clicking the title bar does nothing too. It works with other themes.

So which theme you pointed to? XFwm4 or Gtk+?

Regards.

**Comment by stelariusinfinitek** [comment] 2016-05-17 11:24
If I open Appearance (in the Settings) and choose Arc Darker for example, the maximize button works.

**Comment by tista500** [comment] 2016-05-18 13:33
> If I open Appearance (in the Settings)

It means it seemed to be related to Gtk+ 3.20 theming... So any other Gtk+ 3 based applications had similar issues, or EasyTag specific?

Regards.

**Comment by bil-elmoussaoui** [comment] 2016-05-18 13:47
I can confirm that this happens only with EasyTag with Adapta theme

**Comment by tista500** [comment] 2016-05-18 14:20
All I could find is here: https://bugs.archlinux.org/task/36688

Seems EasyTag may have such "window-size limit" to protect un-scrollable right-most pane. If so, it depend on your font-size, screen resolution and theme's spacing factors.

[Rough testing]
* Set tiny font to shrink the widget sizes (Because Adapta is font-scaling-based scalable Gtk+ theme), less than 9pt or 8pt. And then check maximizing was re-enabled or not...

If application-specific limit in its GtkWindow, unfortunately I could not help you.

Regards.

**Comment by stelariusinfinitek** [comment] 2016-05-18 19:30
Yep, it works if I set the font to 8pt, but it's too small. Good to know. If you can't fix it, I don't think it's a big problem. The theme is gorgeous, keep it healthy! :) I like it so much that I want to donate soon, if you receive donations. 

Have a nice day!

**Comment by tista500** [comment] 2016-05-19 03:00
@stelariusinfinitek,

Indeed, 8pt and 9pt fonts are too tiny.
Anyway this issue causes EasyTag didn't have GtkScrollWindow in right-most pane as a container.

In technically, I could shrink GtkToolBar spacing though, but side-effect will be introduced to any other applications (like Glade, Rhythmbox, and some more)...

Regards.

**Closed by tista500** 2016-05-19 03:00 UTC

**Comment by stelariusinfinitek** [comment] 2016-06-04 23:13
I don't know if you fixed it, but now it works. Maybe because I installed gtk-engines which solves some theming problems with Gimp and Rawtherapee. If someone still experience problems like me, install gtk-engines from your repository. :) (I also installed gtk-engine-murrine and gtk-engine-aurora).
