### ISSUE TITLE
Unreadable text with dark variant

### ISSUE THREAD

**Issue by pschichtel** [tista500/Adapta#15] opened 2016-03-04 17:58 UTC
The image should be enough I guess.

![unreadable-input](https://cloud.githubusercontent.com/assets/526104/13535508/ef8af55e-e23a-11e5-8ad3-f233d3c264a5.png)

Disabled buttons on the top suffer from the same problem, but are a little bit better to read.

**Comment by tista500** [comment] 2016-03-06 15:11
@pschichtel,

There is no optic drive in my home, so I can not reproduce this issue yet, but I've committed some fixes for text colour scheme on GtkTreeView (I don't know whether it was related to this issue or not though).

So could you please check the latest git codes affects to your Sound Juicer or not?

Regards.

**Comment by pschichtel** [comment] 2016-03-06 16:02
Yeah I just recently got an external drive to read old disks.

I have the current stable release installed, which seems to point to the latest commit as of now (https://aur.archlinux.org/packages/adapta-gtk-theme/).
The colors still look the same and I also notices another problem in sound juicer:

![contrast](https://cloud.githubusercontent.com/assets/526104/13555298/1bb46204-e3bd-11e5-877b-12c8a701afa5.png)

**Comment by pschichtel** [comment] 2016-03-06 16:08
The inspector is showing ```GtkEntry:insensitive:backdrop:dir-ltr.entry``` as the CSS selector

**Comment by pschichtel** [comment] 2016-03-06 16:11
![better](https://cloud.githubusercontent.com/assets/526104/13555335/55a3c83c-e3be-11e5-8240-6fb62805d809.png)

Ok it looks better, but only if the window is not in focus

**Comment by pschichtel** [comment] 2016-03-06 16:23
Found another one, this time the trash:

![empty-trash](https://cloud.githubusercontent.com/assets/526104/13555406/184cf088-e3c0-11e5-9014-b0872063ede2.png)

**Comment by tista500** [comment] 2016-03-06 17:44
Sigh... dark variant, dark variant, and dark variant...

Should I stop providing dark variant?

Well, the second (?) issue happened with GtkInfoBar will fix this commit: https://github.com/tista500/Adapta/commit/f206e0ab1d2416245f0974313ec6f39b2f371eb1

But still the primary issue, I can't reproduce on any other GtkApplications, gtk-widget-factory, gtk3-demo, and more...
> The inspector is showing GtkEntry:insensitive:backdrop:dir-ltr.entry as the CSS selector

I know that. But this elements would be included in GtkTreeView (Now I'm seeing SJ's codes) as a parent class. So please let me see how Adwaita draws those labels, could you?

Regards.

**Comment by pschichtel** [comment] 2016-03-06 21:07
> Should I stop providing dark variant?

**Noooooo**

Adwaita:

![focused](https://cloud.githubusercontent.com/assets/526104/13557022/b3efdb28-e3e7-11e5-8533-0c78a08978b2.png)
![unfocused](https://cloud.githubusercontent.com/assets/526104/13557023/b68679b4-e3e7-11e5-883a-f641f2d9620e.png)

1. Focused: dark font
2. Unfocused: even darker font

**Comment by tista500** [comment] 2016-03-07 04:41
@pschichtel,

Hmm, The latest commit https://github.com/tista500/Adapta/commit/8862e285cfd1c9d1d3e37dd9942ac4f22cdd1e6a is now trying to override some foreground colours in GtkTreeView. Any differences?

Regards.

**Comment by pschichtel** [comment] 2016-03-11 11:08
Looks good now

**Closed** 2016-03-11 17:26 UTC
Labels: bug
